#!/bin/bash

for i in {0..9}
do
    cat $(ls DogsVsCats.train[0-9] | grep -v $i) > cvset$i

    svm_light_osx.8.4_i7/svm_learn cvset$i model$i.lin
    echo "Cross Validation Set: $i" >> valacc.lin
    svm_light_osx.8.4_i7/svm_classify DogsVsCats.train$i model$i.lin out$i.lin >> valacc.lin
    echo >> valacc.lin

    svm_light_osx.8.4_i7/svm_learn -t 1 cvset$i model$i.poly
    echo "Cross Validation Set: $i" >> valacc.poly
    svm_light_osx.8.4_i7/svm_classify DogsVsCats.train$i model$i.poly out$i.poly >> valacc.poly
    echo >> valacc.poly
done
