#!/bin/bash

for i in {0..9}
do
    cat $(ls train/DogsVsCats.train[0-9] | grep -v $i) > train/cvset$i

    svm_light_osx.8.4_i7/svm_learn train/cvset$i model/model$i.lin
    echo "Cross Validation Set: $i" >> acc/valacc.lin
    svm_light_osx.8.4_i7/svm_classify train/DogsVsCats.train$i model/model$i.lin out/out$i.lin >> acc/valacc.lin
    echo >> acc/valacc.lin

    svm_light_osx.8.4_i7/svm_learn -t 1 -d 5 train/cvset$i model/model$i.poly
    echo "Cross Validation Set: $i" >> acc/valacc.poly
    svm_light_osx.8.4_i7/svm_classify train/DogsVsCats.train$i model/model$i.poly out/out$i.poly >> acc/valacc.poly
    echo >> acc/valacc.poly
done

svm_light_osx.8.4_i7/svm_learn train/DogsVsCats.train_shuf model/model.lin
svm_light_osx.8.4_i7/svm_classify train/DogsVsCats.train_shuf model/model.lin out/outtr.lin >> acc/tracc.lin
svm_light_osx.8.4_i7/svm_classify DogsVsCats.test_shuf model/model.lin out/outte.lin >> acc/teacc.lin

svm_light_osx.8.4_i7/svm_learn -t 1 -d 5 train/DogsVsCats.train_shuf model/model.poly
svm_light_osx.8.4_i7/svm_classify train/DogsVsCats.train_shuf model/model.poly out/outtr.poly >> acc/tracc.poly
svm_light_osx.8.4_i7/svm_classify DogsVsCats.test_shuf model/model.poly out/outte.poly >> acc/teacc.poly

